language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4b52133077df2ff9ca2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
